// AI Tool Directory — Data Store
const AI_TOOLS = [
  {
  id: 1,
  name: "NoteGPT",
  description: "AI-powered learning assistant that summarizes YouTube videos, PDFs, and articles into smart notes.",
  fullDescription: "NoteGPT is an AI-powered learning and summarization platform designed for students, researchers, and professionals who need to process large volumes of content efficiently. It transforms YouTube videos, PDFs, web articles, PowerPoints, and audio files into concise, structured summaries with timestamps. Beyond basic summarization, NoteGPT generates mind maps, transcripts, presentations, and supports AI chat over any uploaded content. With over 80 million users worldwide, it has become one of the most trusted tools for accelerated learning and knowledge management.",
  category: "Text Generation",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=notegpt.io&sz=64",
  website: "https://notegpt.io",
  features: ["YouTube video summarization", "PDF & document summarization", "AI chat on content", "Mind map generation", "Transcript export", "Chrome extension"]
},
{
  id: 2,
  name: "Pexo",
  description: "Conversational AI video partner that turns a simple description into a fully produced, publish-ready video.",
  fullDescription: "Pexo is a next-generation AI video creation platform that replaces complex prompt engineering with natural conversation. Users simply describe their idea in plain language, and Pexo handles everything — writing the script, planning storyboards, selecting visuals, adding voiceovers, transitions, captions, and background music — delivering a complete, publish-ready video. It integrates multiple cutting-edge AI models including Seedance 2.0, Kling, Claude, GPT, and ElevenLabs to produce cinematic-quality results. Ideal for content creators, marketers, and brands who want polished videos without technical skills.",
  category: "Video",
  rating: 4.6,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=pexo.ai&sz=64",
  website: "https://pexo.ai",
  features: ["Conversational video creation", "Auto script & storyboard", "Multi-model AI integration", "Voiceover & captions", "Lip sync dubbing", "Publish-ready output"]
},
{
  id: 3,
  name: "Magica",
  description: "All-in-one AI platform giving access to GPT, Claude, image generators, and 5000+ pre-built tools for $15/month.",
  fullDescription: "Magica is a comprehensive AI subscription aggregator that provides access to virtually every major AI model and tool under one affordable plan. For $15 per month, users get access to GPT-4, Claude, Gemini, Sora, image generators, video tools, code execution, and over 5,900 pre-built workflow tools for content creation, business automation, and marketing. It integrates seamlessly with Google Drive, Slack, and Gmail, making it a powerful hub for teams looking to replace multiple expensive AI subscriptions with a single, cost-effective platform.",
  category: "Text Generation",
  rating: 4.4,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=magica.com&sz=64",
  website: "https://magica.com",
  features: ["Access to all major AI models", "5000+ pre-built tools", "Video & image generation", "Google Drive & Slack integration", "Multi-model comparison", "Team collaboration"]
},
{
  id: 4,
  name: "AI Overview Optimizer",
  description: "SEO tool that tracks and optimizes your content for Google AI Overviews and answer engine visibility.",
  fullDescription: "AI Overview Optimizer is a specialized SEO platform designed to help brands and content teams gain visibility in Google AI Overviews, ChatGPT, Perplexity, and other answer engines. It tracks how often your content appears in AI-generated search results, analyzes the sources AI prefers, and provides actionable recommendations to optimize your pages for inclusion. As AI Overviews now appear in over 57% of searches, traditional SEO strategies alone are insufficient — this tool bridges that gap with dedicated AI search visibility tracking and content optimization guidance.",
  category: "Text Generation",
  rating: 4.3,
  pricing: "Paid",
  icon: "https://www.google.com/s2/favicons?domain=seranking.com&sz=64",
  website: "https://seranking.com",
  features: ["Google AI Overview tracking", "Answer engine optimization", "Keyword visibility scoring", "Competitor analysis", "Content recommendations", "Weekly trend reports"]
},
{
  id: 5,
  name: "Pixmax AI",
  description: "Credit-based AI creative workspace for generating videos, images, scripts, audio, and campaign assets.",
  fullDescription: "Pixmax AI is a unified creative workspace built for marketers, content creators, and agencies who need to produce diverse AI-generated assets efficiently. Operating on a credit-based system, it provides access to video generation, image creation, script writing, audio production, and campaign template tools — all within a single visual canvas. Pixmax eliminates the need to juggle multiple AI subscriptions by centralizing creative production, making it easy to brief, generate, review, and export polished assets for any marketing channel.",
  category: "Image",
  rating: 4.4,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=pixmax.ai&sz=64",
  website: "https://pixmax.ai",
  features: ["Video generation", "AI image creation", "Script writing", "Audio production", "Campaign templates", "Visual canvas workspace"]
},
{
  id: 6,
  name: "TeraBox AI",
  description: "All-in-one AI workspace with 1TB free cloud storage plus tools for presentations, writing, images, and video.",
  fullDescription: "TeraBox AI combines generous cloud storage with a growing suite of AI-powered productivity tools. Users get 1TB of free storage for documents, photos, and videos, alongside AI features including a presentation maker, essay writer, image generator, video creator, and research assistant. The platform supports cross-device access on web, desktop, and mobile, with real-time sync and privacy protection. TeraBox is particularly popular among students and small businesses looking for an affordable, all-in-one storage and AI productivity solution with a low barrier to entry.",
  category: "Text Generation",
  rating: 4.2,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=terabox.com&sz=64",
  website: "https://terabox.com",
  features: ["1TB free cloud storage", "AI presentation maker", "Essay & writing tools", "Image generation", "Video creation", "Cross-device sync"]
},
{
  id: 7,
  name: "Blaze",
  description: "AI marketing platform that autonomously creates, schedules, and publishes brand content across all channels.",
  fullDescription: "Blaze is an autonomous AI marketing platform designed for solo marketers, small businesses, and agencies who need consistent, high-quality content without a large team. It learns your brand voice, builds a marketing strategy, then automatically generates blogs, social media posts, newsletters, and ad copy tailored to your style. Blaze's AI learning loop improves content quality over time by analyzing engagement data. With direct integrations to LinkedIn, Instagram, Facebook, Twitter, and major CMS platforms, it can schedule and publish content entirely hands-free, functioning as a virtual marketing department.",
  category: "Text Generation",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=blaze.ai&sz=64",
  website: "https://blaze.ai",
  features: ["Brand voice learning", "Autonomous content creation", "Multi-platform scheduling", "AI learning loop", "SEO optimization", "Analytics & insights"]
},
{
  id: 8,
  name: "Coursebox AI Tutor",
  description: "AI-powered course creation and tutoring platform that builds interactive courses from any existing content.",
  fullDescription: "Coursebox AI is a comprehensive e-learning platform that uses artificial intelligence to help educators, trainers, and organizations create professional online courses in minutes rather than days. It converts existing videos, documents, websites, and presentations into structured course content with quizzes, assessments, and interactive elements automatically. The AI Tutor chatbot is trained on course content to provide learners with 24/7 personalized support in 100+ languages. Automated grading, certificate issuance, and LMS integration make it a complete end-to-end solution for educational content creation and delivery.",
  category: "Text Generation",
  rating: 4.6,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=coursebox.ai&sz=64",
  website: "https://coursebox.ai",
  features: ["AI course creation", "AI tutor chatbot", "Automated grading", "100+ language support", "Certificate generation", "LMS integration"]
},
{
  id: 9,
  name: "Fotor",
  description: "Online AI photo editor and design platform with background removal, enhancement, and image generation.",
  fullDescription: "Fotor is a versatile online photo editing and graphic design platform that combines traditional editing tools with powerful AI capabilities. Its AI toolkit includes one-click photo enhancement, background removal, object cleanup, face retouching, AI image generation, and the newly launched Sisi AI agent that understands natural language editing commands. With 100,000+ design templates, batch editing, and a generous free plan, Fotor serves social media creators, marketers, e-commerce sellers, and casual users who need fast, professional results without Photoshop complexity. Available on web and mobile with no software installation required.",
  category: "Image",
  rating: 4.4,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=fotor.com&sz=64",
  website: "https://fotor.com",
  features: ["AI photo enhancement", "Background removal", "AI image generation", "100K+ templates", "Batch editing", "Natural language AI agent (Sisi)"]
},
{
  id: 10,
  name: "Clico",
  description: "Browser extension that embeds AI assistance directly into every text field across any website.",
  fullDescription: "Clico is a lightweight but powerful browser extension that brings AI capabilities directly to wherever you type on the web. Instead of switching between tabs to use AI tools, Clico places an AI assistant inside every text field — whether you're composing emails in Gmail, writing posts on LinkedIn, filling forms, or chatting in any web app. It supports text improvement, tone adjustment, summarization, translation, and custom AI prompts inline, making it ideal for professionals who want AI assistance seamlessly integrated into their existing browser-based workflows without disrupting their focus.",
  category: "Text Generation",
  rating: 4.3,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=clico.ai&sz=64",
  website: "https://clico.ai",
  features: ["In-browser AI assistance", "Works in every text field", "Tone & style adjustment", "Translation support", "Email composition help", "Custom AI prompts"]
},  
{
  id: 11,
  name: "Base44",
  description: "AI app builder that creates fully functional web apps and websites from plain-English prompts — no coding needed.",
  fullDescription: "Base44 is a no-code AI app builder, recently acquired by Wix, that lets anyone create complete web applications by simply describing what they want in natural language. The platform automatically generates the UI, database, authentication, and backend logic — handling the entire technical stack so users can focus on their idea rather than implementation. Base44 includes a visual editor for fine-tuning designs, in-app code editing for developers who want more control, and supports selecting different AI models for app generation. It's popular among founders, marketers, and designers building MVPs and internal tools quickly without hiring developers.",
  category: "Coding",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=base44.com&sz=64",
  website: "https://base44.com",
  features: ["Natural language app generation", "Auto database & authentication", "Visual editor", "In-app code editing", "Multiple AI model selection", "Free custom domain (paid plans)"]
},
{
  id: 12,
  name: "i10X",
  description: "All-in-one AI workspace giving unified access to ChatGPT, Claude, Gemini, and 500+ specialized AI agents from $8/month.",
  fullDescription: "i10X is a unified AI workspace designed to replace dozens of separate AI subscriptions with a single affordable plan. It provides direct access to leading language models including GPT-5, Claude, Gemini, Perplexity, and Grok, alongside over 500 specialized AI agents covering content creation, image and video generation, document analysis, legal work, SEO, and business automation. With Kling and Veo AI video tools, ChatPDF-style document chat, and cross-agent memory, i10X consolidates an entire AI toolkit into one workspace — saving users up to 90% compared to maintaining individual subscriptions for each tool.",
  category: "Text Generation",
  rating: 4.4,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=i10x.ai&sz=64",
  website: "https://i10x.ai",
  features: ["Access to GPT-5, Claude, Gemini, Grok", "500+ specialized AI agents", "AI video generation (Kling, Veo)", "PDF & document chat", "Cross-agent memory", "Image generation & upscaling"]
},
{
  id: 13,
  name: "Higgsfield",
  description: "AI video generator with cinematic camera controls, character consistency, and access to Sora, Veo, and Kling models.",
  fullDescription: "Higgsfield is a premium AI video generation platform built for creators who want director-level control over their content. It offers unique camera movements (dolly shots, crash zooms, overhead angles) and cinematic presets that mimic professional filmmaking techniques. Higgsfield's Soul ID and WAN Camera Controls maintain character consistency across multiple scenes, while integrated audio tools handle text-to-speech, voice swaps, and multilingual lip-synced translations. The platform provides access to top-tier models including Sora 2, Veo 3.1, and Kling 3.0 within a single credit-based subscription, covering the entire video production pipeline.",
  category: "Video",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=higgsfield.ai&sz=64",
  website: "https://higgsfield.ai",
  features: ["Cinematic camera controls", "Character consistency (Soul ID)", "Access to Sora, Veo, Kling", "AI voiceover & lip sync", "Multilingual translation", "Cinematic presets"]
},
{
  id: 14,
  name: "Munch Studio",
  description: "AI social media manager that builds a content strategy and auto-generates and publishes posts from your business website.",
  fullDescription: "Munch Studio is a done-for-you AI social media platform that takes over the entire content workflow for small businesses and entrepreneurs. Users simply enter their website URL, and the AI reads the brand, builds a custom content strategy, and starts generating on-brand posts automatically. It learns your visual style and tone, repurposes long-form content into short clips, and intelligently schedules posts for peak engagement across Instagram, Facebook, LinkedIn, and more. Used by over 20,000 businesses including Salesforce and HubSpot, Munch Studio eliminates the blank-canvas problem entirely — there's no prompt to write or template to fill.",
  category: "Text Generation",
  rating: 4.4,
  pricing: "Paid",
  icon: "https://www.google.com/s2/favicons?domain=munchstudio.com&sz=64",
  website: "https://munchstudio.com",
  features: ["Auto content strategy from website", "AI brand voice replication", "Smart scheduling", "Video repurposing", "Performance analytics", "Cross-platform publishing"]
},
{
  id: 15,
  name: "Vidnoz",
  description: "AI video generator with 1,900+ talking avatars, voice cloning, and text-to-video for marketing and training videos.",
  fullDescription: "Vidnoz is an accessible AI video creation platform that lets anyone produce professional videos without cameras, actors, or studios. It offers one of the largest avatar libraries available with over 1,900 AI avatars and 890+ realistic voices across multiple languages. Users can create custom avatars from their own photos, clone their voice, swap faces, and convert scripts directly into narrated videos with natural lip-sync and gestures. Beyond avatars, Vidnoz includes face swap, talking photos, AI dance generation, and video translation tools — making it a versatile, budget-friendly choice for marketing, training, and educational content.",
  category: "Video",
  rating: 4.3,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=vidnoz.com&sz=64",
  website: "https://vidnoz.com",
  features: ["1,900+ AI avatars", "890+ AI voices", "Voice cloning", "Text-to-video", "Face swap & talking photos", "Video translation"]
},
{
  id: 16,
  name: "Klap",
  description: "AI tool that turns long videos into viral short clips with auto-captions, reframing, and virality scoring.",
  fullDescription: "Klap is an AI-powered video repurposing tool used by over 1.5 million creators to transform long-form content into short, social-ready clips. Simply paste a YouTube link or upload a video, and Klap's AI analyzes the entire recording to identify the most engaging moments — quotable statements, high-energy segments, and natural topic boundaries — then automatically cuts them into 15-90 second clips. Each clip is auto-reframed for vertical platforms, gets dynamic synced captions, and receives a virality score to help creators prioritize which clips to post. Klap supports direct publishing to TikTok, YouTube, Instagram, and LinkedIn.",
  category: "Video",
  rating: 4.4,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=klap.app&sz=64",
  website: "https://klap.app",
  features: ["AI clip generation from long videos", "Auto-reframing for vertical platforms", "Dynamic synced captions", "Virality scoring", "Multi-platform publishing", "AI dubbing"]
},
{
  id: 17,
  name: "Wispr Flow",
  description: "AI voice dictation tool that turns natural speech into clean, formatted text in any app, 4x faster than typing.",
  fullDescription: "Wispr Flow is a system-wide AI voice dictation application that converts natural speech into polished, formatted text inside any application on Mac, Windows, iOS, and Android. Activated via a simple hotkey, it transcribes speech in real time while AI layers remove filler words, fix grammar, apply intelligent punctuation, and adapt formatting to the context of the app you're using — whether that's Gmail, Slack, Notion, or VS Code. Its standout Command Mode lets users edit, summarize, or rephrase text using only their voice. With over 8,500 App Store ratings averaging 4.8/5 and backing from Amazon, Nvidia, and Vercel, Wispr Flow has become the leading premium dictation tool for professionals who think faster than they type.",
  category: "Text Generation",
  rating: 4.6,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=wisprflow.ai&sz=64",
  website: "https://wisprflow.ai",
  features: ["System-wide voice dictation", "AI text cleanup & formatting", "Command Mode (voice editing)", "100+ language support", "Cross-platform (Mac, Windows, iOS, Android)", "HIPAA & SOC 2 compliant"]
},
{
  id: 18,
  name: "Pictory",
  description: "AI video creator that turns blog posts, scripts, and long-form content into short, engaging videos automatically.",
  fullDescription: "Pictory is an AI-powered video creation platform that transforms text-based content into professional videos without requiring any editing skills. It excels at converting blog posts into video scripts, repurposing long videos into short social clips, and adding automatic captions for accessibility and engagement. The platform includes access to over 2 million royalty-free stock videos from Storyblocks, dozens of natural AI voiceover voices, and thousands of music tracks. Branded templates keep output consistent with your visual identity, and team collaboration features make it suitable for marketing departments and agencies producing video content at scale.",
  category: "Video",
  rating: 4.5,
  pricing: "Paid",
  icon: "https://www.google.com/s2/favicons?domain=pictory.ai&sz=64",
  website: "https://pictory.ai",
  features: ["Text-to-video generation", "2M+ royalty-free stock clips", "Auto captioning", "AI voiceovers", "Branded templates", "Long-to-short video repurposing"]
},
{
  id: 19,
  name: "AiMEY",
  description: "Agentic AI coworker that joins meetings, takes notes, executes tasks, and updates your tools automatically.",
  fullDescription: "AiMEY is an AI-powered project assistant that functions as an agentic coworker for teams. It joins meetings to listen and transcribe in real time, automatically generates structured notes and action items, then executes the follow-through — creating tasks, sending reminders, updating CRMs, and notifying stakeholders without manual input. AiMEY integrates seamlessly with the tools teams already use, including Microsoft Teams, Zoom, Outlook, Slack, Jira, Monday.com, and HubSpot. By handling the administrative overhead of meetings and task tracking, AiMEY lets teams focus on decisions and strategy while it manages the follow-up.",
  category: "Text Generation",
  rating: 4.2,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=aimey.ai&sz=64",
  website: "https://aimey.ai",
  features: ["AI meeting notes & transcription", "Automatic task creation", "CRM auto-updates", "Multi-platform integrations", "Reminders & follow-ups", "Team collaboration"]
},
{
  id: 20,
  name: "Novamira",
  description: "WordPress AI agent plugin that gives Claude, Cursor, and other AI clients full native access to your WordPress site via MCP.",
  fullDescription: "Novamira is a self-hosted WordPress plugin that connects MCP-compatible AI clients — including Claude Code, Cursor, VS Code, and Windsurf — directly to your WordPress environment at the PHP level. Unlike REST API-based tools, Novamira gives AI agents full access to execute PHP, query the database, read and write files, manage plugins and themes, and build pages in Elementor, Bricks, WooCommerce, and 17+ other builders. All data stays on your server — nothing passes through Novamira's servers. Built for development and staging environments, it includes sandboxed PHP execution with crash recovery and session memory so your AI remembers project conventions across conversations.",
  category: "Coding",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=novamira.ai&sz=64",
  website: "https://novamira.ai",
  features: ["Full PHP execution inside WordPress", "MCP integration with Claude, Cursor, VS Code", "Database queries & file editing", "17+ builder support (Elementor, Bricks, WooCommerce)", "Zero data on external servers", "Session memory for project conventions"]
},
{
  id: 21,
  name: "NoimosAI",
  description: "Autonomous AI marketing platform with specialized agents for SEO, content, social media, and advertising — running 24/7.",
  fullDescription: "NoimosAI is an all-in-one autonomous marketing platform that functions as a full AI marketing department for solopreneurs, startups, and growing businesses. It deploys specialized AI agents that work simultaneously across different marketing channels — one monitoring competitor mentions, another optimizing content for AI search visibility, another managing ad campaigns — all coordinating and sharing insights automatically. The platform learns from real-time market trends and user feedback to continuously refine strategy. With a customizable dashboard using block editors, a natural language chat interface for task assignment, and 24/7 autonomous operation, NoimosAI aims to replace over 80% of manual marketing work at a fraction of the cost of hiring specialists.",
  category: "Text Generation",
  rating: 4.3,
  pricing: "Paid",
  icon: "https://www.google.com/s2/favicons?domain=noimosai.com&sz=64",
  website: "https://noimosai.com",
  features: ["Specialized AI marketing agents", "SEO & GEO optimization", "24/7 autonomous operation", "AI ad campaign management", "Real-time market trend analysis", "Custom dashboard with block editor"]
},
{
  id: 22,
  name: "OpusClip",
  description: "AI video clipping tool used by 16 million creators to turn long videos into viral short clips for TikTok, Reels, and Shorts.",
  fullDescription: "OpusClip is an AI-powered tool designed to automate the creation of short-form video content from longer videos. It analyzes long recordings to identify the most engaging moments — compelling hooks, high-energy segments, quotable statements — and automatically cuts them into 15–90 second clips. The proprietary ReframeAnything AI model resizes each clip to 9:16, 16:9, or 1:1 while intelligently tracking subjects to keep them perfectly framed. Dynamic animated captions, a virality score (1–100), filler word removal, and one-click publishing to TikTok, Instagram, YouTube, and LinkedIn make it a complete short-form content pipeline. Used by over 16 million creators worldwide with a free plan available.",
  category: "Video",
  rating: 4.6,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=opus.pro&sz=64",
  website: "https://opus.pro",
  features: ["AI clip detection from long videos", "ReframeAnything auto-reframing", "Dynamic animated captions", "Virality score (1-100)", "Filler word removal", "One-click multi-platform publishing"]
},
{
  id: 23,
  name: "Artlist",
  description: "All-in-one creative platform with royalty-free music, stock footage, AI video generation, and Veo 3 access for video creators.",
  fullDescription: "Artlist started as a curated royalty-free music licensing library for filmmakers and has evolved into a comprehensive AI-powered creative platform. It now combines a massive catalog of music, sound effects, stock footage (up to 8K), video templates, and LUTs with cutting-edge AI tools for video generation, image creation, AI voiceovers, and AI music composition. Artlist is one of the first platforms to offer access to Google's Veo 3 cinema-quality video generator alongside Kling and Seedance models. The Artlist Library Extension integrates music, SFX, and voiceover catalogs directly into Premiere Pro. All published projects retain their commercial license forever, even after subscription ends — making it a trusted choice for professional video creators, filmmakers, and marketing teams worldwide.",
  category: "Audio",
  rating: 4.7,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=artlist.io&sz=64",
  website: "https://artlist.io",
  features: ["Royalty-free music & SFX library", "8K stock footage", "AI video generation (Veo 3, Kling, Seedance)", "AI image & voiceover tools", "Premiere Pro extension", "Perpetual commercial license"]
},
{
  id: 24,
  name: "ClearCRM",
  description: "All-in-one CRM platform for small teams combining sales, marketing, projects, invoicing, and customer support in one place.",
  fullDescription: "ClearCRM is a comprehensive customer relationship management platform built specifically for small businesses and growing teams who need to manage their entire customer journey without juggling multiple disconnected tools. It unifies sales pipeline management, lead capture, email marketing, landing page building, project tracking, invoicing, payment processing, and customer support ticketing into a single fast workspace. AI-powered features assist with generating emails, transcribing calls, creating images, and surfacing data-driven insights. Founded in 2025, ClearCRM positions itself as the go-to all-in-one solution for teams that need enterprise-grade CRM functionality at an accessible price point.",
  category: "Text Generation",
  rating: 4.2,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=clearcrm.com&sz=64",
  website: "https://clearcrm.com",
  features: ["Sales pipeline management", "Email marketing & automation", "AI email & call transcription", "Invoicing & payment processing", "Project & task tracking", "Customer support ticketing"]
},
{
  id: 25,
  name: "GetMind",
  description: "AI-powered advertising agency platform for managing clients, campaigns, projects, and performance from one dashboard.",
  fullDescription: "GetMind is a comprehensive agency management platform designed for advertising agencies, marketing firms, and creative studios that need to streamline their operations end-to-end. It provides an intuitive real-time dashboard for monitoring project statuses, allocating resources, and overseeing campaign performance across multiple clients. Core features include CRM for client relationship tracking, multi-channel campaign planning and execution, time tracking, billing, creative asset management, and detailed analytics reporting covering reach, engagement, conversion rates, and ROI. With a freemium pricing model and integrations with popular project management and analytics tools, GetMind helps agencies deliver better results with less operational overhead.",
  category: "Text Generation",
  rating: 4.2,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=getmind.app&sz=64",
  website: "https://getmind.app",
  features: ["Real-time agency dashboard", "Multi-channel campaign management", "Client CRM & communication", "Time tracking & billing", "Creative asset management", "Performance analytics & ROI reporting"]
},
{
  id: 26,
  name: "B12",
  description: "AI website builder that creates professional websites in 60 seconds with built-in scheduling, invoicing, and email marketing.",
  fullDescription: "B12 is an AI-powered website builder designed for service-based businesses, freelancers, and small teams who need a professional online presence without technical skills. It generates a complete, mobile-optimized website in 60 seconds from a short prompt, then combines it with a full business toolkit including online scheduling, client intake forms, payment processing, invoicing, email marketing, and an AI assistant for editing and updates. Human designers review AI-generated sites to ensure quality. With a free Starter plan and paid plans from $49/month, B12 replaces the need for separate tools like Calendly, FreshBooks, and Mailchimp — consolidating them into one platform.",
  category: "Coding",
  rating: 4.3,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=b12.io&sz=64",
  website: "https://b12.io",
  features: ["AI website generation in 60 seconds", "Online scheduling & booking", "Invoicing & payment processing", "Email marketing tools", "Client intake forms", "AI assistant for site editing"]
},
{
  id: 27,
  name: "Genspark",
  description: "AI super-agent that turns prompts into structured Sparkpages, slides, spreadsheets, and research reports with cited sources.",
  fullDescription: "Genspark is an AI-powered productivity platform that goes beyond chatbot responses by generating structured, publication-ready outputs from natural language prompts. Its specialized AI agents — including Super Agent, Docs, Sheets, Slides, and Clip Genius — work together to research topics, compile cited reports, build spreadsheets, create presentations, and summarize web content into polished Sparkpages. With access to top models including GPT-4, Claude, and Flux, Genspark bridges the gap between a research assistant and a lightweight productivity suite. Having reached $155M ARR in 2025, it has become a go-to tool for freelancers, content creators, and small teams seeking a cost-effective alternative to multiple AI subscriptions.",
  category: "Text Generation",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=genspark.ai&sz=64",
  website: "https://genspark.ai",
  features: ["AI Sparkpage generation", "Research reports with citations", "AI slides & spreadsheets", "Multi-model access (GPT-4, Claude, Flux)", "AI phone call agent", "Clip Genius video summarization"]
},
{
  id: 28,
  name: "Creatify",
  description: "AI video ad generator that turns product URLs into high-converting video ads with AI avatars, scripts, and voiceovers in minutes.",
  fullDescription: "Creatify is an AI-powered video ad creation platform whose core differentiator is its URL-to-video technology. Users paste a product link from Shopify, Amazon, or any e-commerce site, and Creatify automatically scrapes images, text, and pricing to generate 5–10 complete, ready-to-run video ad variations. With over 1 million advertisers and a 4.8/5 G2 rating, it reduces production costs by up to 90%. The AdMax Performance Suite includes an AI Ad Library for competitor analysis, an AI scriptwriter, ROAS tracking, and a built-in video editor. Over 1,000 AI avatars, batch creation for multiple ad variations, and direct publishing to Meta and Google make Creatify a complete creative automation engine for performance marketers, ecommerce brands, and agencies.",
  category: "Video",
  rating: 4.7,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=creatify.ai&sz=64",
  website: "https://creatify.ai",
  features: ["URL-to-video ad generation", "1,000+ AI avatars", "AdMax competitor ad analysis", "Batch ad creation", "Built-in video editor", "Direct Meta & Google publishing"]
},
{
  id: 29,
  name: "Dropmagic",
  description: "AI Shopify store builder that turns any AliExpress or Amazon product URL into a complete branded store in minutes — free to build.",
  fullDescription: "Dropmagic is an AI-powered store builder for Shopify that transforms any product URL from AliExpress, Amazon, or Alibaba into a complete, conversion-optimized ecommerce store within minutes. It automatically generates store branding, logos, color palettes, product descriptions, and mobile-optimized layouts — all trained on 8-figure brand copy for copy that actually converts. The platform is free to generate and customize stores; you only pay $79/month when ready to publish to Shopify. Features include one-click product import with inventory sync, 57+ conversion-focused page sections, AI image generation, checkout optimization, and integrations with Klaviyo, TikTok Pixel, Google Analytics, and more. Ideal for dropshippers who want to test multiple product ideas rapidly.",
  category: "Coding",
  rating: 4.4,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=dropmagic.ai&sz=64",
  website: "https://dropmagic.ai",
  features: ["Product URL to Shopify store", "AI brand & copy generation", "57+ conversion-focused sections", "One-click product import", "AI image generation", "Free to build, pay to publish"]
},
{
  id: 30,
  name: "Blitz Rocket",
  description: "AI-powered viral marketing platform for running contests, giveaways, and referral campaigns to grow email lists and social followers.",
  fullDescription: "Blitz Rocket (formerly VYPER) is an AI-powered viral marketing platform that helps brands grow their audience through gamified campaigns. It enables businesses to launch contests, giveaways, referral programs, and UGC collection campaigns that motivate participants to engage and share organically — without relying solely on paid ads. AI-verified action tracking prevents fraud and ensures only genuine entries are counted. Features include points-based reward systems, content-gated rewards, real-time analytics, API integration for developers, and pre-made campaign templates for fast launch. Used by thousands of brands including musicians, e-commerce stores, SaaS companies, and content creators, Blitz Rocket offers a free plan with no credit card required.",
  category: "Text Generation",
  rating: 4.3,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=blitzrocket.com&sz=64",
  website: "https://blitzrocket.com",
  features: ["Viral contest & giveaway builder", "Referral program management", "AI fraud detection", "Points-based reward system", "UGC campaign collection", "Real-time analytics dashboard"]
},
{
  id: 31,
  name: "HelpCrunch",
  description: "All-in-one AI customer support platform combining live chat, AI agents, help desk, knowledge base, and email marketing.",
  fullDescription: "HelpCrunch is an AI-powered customer service platform that unifies live chat, AI agents, shared inbox, help desk ticketing, knowledge base, and email marketing automation into one workspace. AI Agents are trained exclusively on your content and can autonomously handle up to 80% of customer questions, freeing your support team to focus on complex cases. The platform supports omnichannel communication across website chat, email, and social media, with an AI Editor to help agents write polished responses faster. Used by startups and SMBs as a cost-effective Intercom alternative, HelpCrunch offers a 14-day free trial with no credit card required and transparent per-agent pricing.",
  category: "Text Generation",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=helpcrunch.com&sz=64",
  website: "https://helpcrunch.com",
  features: ["AI agents (handles 80% of queries)", "Omnichannel live chat", "Help desk & ticketing", "Knowledge base builder", "Email marketing automation", "AI editor for agent replies"]
},
{
  id: 32,
  name: "MakeUGC",
  description: "AI platform that creates realistic UGC-style video ads with AI avatars holding your product — no filming or actors needed.",
  fullDescription: "MakeUGC is an AI-powered content creation platform that generates realistic user-generated content (UGC) style video ads without filming, actors, or studios. Its standout Product-in-Hand feature lets AI avatars physically hold and showcase your product on screen, producing authentic-looking TikTok and Instagram Reel ads that convert. Users upload product details or links, choose from 100+ AI avatars, write or auto-generate a script, and get a finished video in minutes. Batch Mode enables bulk creation for A/B testing multiple hooks simultaneously. With 50+ language support, lip-sync accuracy, full content ownership rights, and a Video Agent for analyzing and rebuilding competitor ad styles, MakeUGC is built for eCommerce brands and performance marketers.",
  category: "Video",
  rating: 4.4,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=makeugc.ai&sz=64",
  website: "https://makeugc.ai",
  features: ["Product-in-Hand AI avatars", "100+ realistic AI avatars", "AI script & hook generator", "Batch video creation", "50+ language lip-sync", "Full content ownership rights"]
},
{
  id: 33,
  name: "Hermes Agent",
  description: "Free open-source self-improving AI agent that learns from every task, builds reusable skills, and connects to Telegram, Discord, and Slack.",
  fullDescription: "Hermes Agent is a free, open-source autonomous AI agent developed by Nous Research with over 64,000 GitHub stars. It is the only open-source agent framework with a closed learning loop — it completes tasks, writes reusable skill documents from experience, stores outcomes in persistent memory, and improves its approach over time. Benchmarks show an agent using self-created skills completes research tasks 40% faster than a fresh instance. It connects to Telegram, Discord, Slack, WhatsApp, and Signal, supports 200+ AI models via OpenRouter, and runs on a $5/month VPS with all data stored locally and zero telemetry. Fully MIT licensed with no paid tiers — you only pay for hosting and LLM API usage.",
  category: "Coding",
  rating: 4.6,
  pricing: "Free",
  icon: "https://www.google.com/s2/favicons?domain=nousresearch.com&sz=64",
  website: "https://github.com/NousResearch/hermes-agent",
  features: ["Self-improving skill memory", "64,200+ GitHub stars", "200+ AI model support", "Multi-platform messaging (Telegram, Discord, Slack)", "Zero telemetry, local data storage", "MIT licensed — completely free"]
},
{
  id: 34,
  name: "Guideless",
  description: "AI guide builder that turns any browser workflow into a polished, narrated video tutorial in minutes — no editing required.",
  fullDescription: "Guideless is an AI-powered guide creation tool that transforms any browser workflow into a polished, narrated video tutorial automatically. Using its Chrome extension, users simply click through their process as normal — Guideless captures every step, adds AI-written narration, natural voiceover from a library of 42+ languages, smart zooms, highlights, and captions, delivering a share-ready guide instantly. Use cases include product walkthroughs, customer onboarding, employee training, and support documentation. Features include sensitive data blurring, 4K MP4 export, team workspaces for co-creation, an analytics dashboard showing views and drop-off points, and one-click guide duplication for translations. The free plan includes 3 guides with full AI narration — no credit card required.",
  category: "Video",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=guideless.ai&sz=64",
  website: "https://guideless.ai",
  features: ["Chrome extension workflow capture", "AI narration & voiceover (42+ languages)", "Smart zooms & highlights", "Sensitive data blurring", "4K MP4 export", "Guide analytics & drop-off tracking"]
},
{
  id: 35,
  name: "iDox.ai Guardrail",
  description: "Real-time AI security platform that monitors, intercepts, and blocks sensitive data from being shared with AI tools like ChatGPT.",
  fullDescription: "iDox.ai Guardrail is a real-time AI security and governance platform that runs as an agent on desktop and mobile devices, monitoring everything users type or paste into AI tools like ChatGPT, Microsoft Copilot, and Gemini. It intercepts sensitive data — including source code, personal information, financial records, and confidential documents — before it reaches AI systems, enforcing company AI acceptable use policies in real time. For enterprises, it provides centralized governance, prompt injection detection, AI activity audit logs, and compliance support for GDPR, HIPAA, CCPA, and SOX. A Family Edition protects children from harmful AI content with automatic topic blocking. Trusted by over 15,000 organizations worldwide.",
  category: "Coding",
  rating: 4.4,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=idox.ai&sz=64",
  website: "https://idox.ai",
  features: ["Real-time data leak prevention", "Prompt injection detection", "Endpoint-level AI monitoring", "Centralized policy governance", "GDPR, HIPAA & SOX compliance", "Family Edition for child safety"]
},
{
  id: 36,
  name: "Floor Plan AI (Maket)",
  description: "AI floor plan generator that creates and edits real, dimensioned residential layouts through simple conversation.",
  fullDescription: "Maket is an AI-powered floor plan generator built for residential design, standing out as the only tool in its category that lets users both generate and edit floor plans through natural conversation. Its generative AI produces real, editable floor plans with accurate dimensions — simply describe your space requirements and Maket creates layout options, which can then be refined further through chat. The workspace supports exploring multiple visual directions for the same plan, making it easy to compare options before committing. With a free tier offering 50 credits and paid plans from $20/month for 300 credits, Maket serves homeowners planning renovations, real estate agents needing listing visuals, and designers prototyping layouts quickly without CAD software.",
  category: "Image",
  rating: 4.3,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=maket.ai&sz=64",
  website: "https://maket.ai",
  features: ["Conversational floor plan generation", "Real, editable dimensions", "Multiple layout exploration", "Refine plans via chat", "Free tier with 50 credits", "Residential design focus"]
},
{
  id: 37,
  name: "Friend",
  description: "Wearable AI companion device that listens, remembers, and chats with you via text — a $99 one-time purchase, no subscription.",
  fullDescription: "Friend is a small, glowing wearable AI companion device that clips onto clothing or hangs as a pendant, equipped with a microphone to passively listen to your day. It communicates exclusively through text messages via a companion smartphone app — a deliberate design choice that feels familiar and comfortable. Unlike productivity assistants like Siri, Friend is built purely for emotional companionship: a presence that remembers your conversations and can initiate chats on its own through a 'Free Will' feature. Priced at a one-time $99 with no subscription required, all memories are tied to the physical device — if lost, they're gone forever, reinforcing the personal, irreplaceable nature of the relationship. Initially available in the US and Canada.",
  category: "Audio",
  rating: 3.9,
  pricing: "Paid",
  icon: "https://www.google.com/s2/favicons?domain=friend.com&sz=64",
  website: "https://friend.com",
  features: ["Wearable always-listening device", "Text-based AI conversations", "One-time $99 cost, no subscription", "'Free Will' proactive messaging", "Persistent on-device memory", "Emotional companionship focus"]
},
{
  id: 38,
  name: "Whimsical AI (Flowchart AI)",
  description: "AI diagramming tool powered by Claude that turns text prompts into editable flowcharts, mind maps, and sequence diagrams in seconds.",
  fullDescription: "Whimsical AI is a fast, single-purpose AI diagramming tool powered by Claude. Type a prompt describing a process, decision tree, or system, and within about 4 seconds Whimsical returns a clean, editable flowchart that typically needs zero manual layout adjustments. Beyond flowcharts, it generates mind maps, sequence diagrams, and user flows on an infinite collaborative canvas with real-time team editing. A built-in MCP server runs locally on the desktop app, allowing AI coding agents like Claude, Cursor, and Codex to read and write directly to your Whimsical workspace. With integrations for Notion, Jira, and Slack, plus a generous free tier and paid plans starting at $6/month, Whimsical is ideal for product managers, engineers, and teams who want to turn brainstorms into structured visuals instantly.",
  category: "Coding",
  rating: 4.6,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=whimsical.com&sz=64",
  website: "https://whimsical.com/ai",
  features: ["Text-to-flowchart in ~4 seconds", "Powered by Claude AI", "Mind maps & sequence diagrams", "Local MCP server for AI agents", "Real-time team collaboration", "Notion, Jira & Slack integration"]
},  
{
  id: 39,
  name: "Image to Excel (RowSpeak)",
  description: "AI tool that converts photos, screenshots, and scanned tables into editable Excel spreadsheets with 99% accuracy.",
  fullDescription: "RowSpeak's Image to Excel converter solves a common data entry headache: information trapped in screenshots, scanned reports, invoices, and phone photos. Using AI-powered structure detection (rather than basic OCR), it accurately parses entire grids — rows, columns, cell alignment, and merged cells — to reconstruct a clean, ready-to-use spreadsheet that mirrors the original image. Users upload a PNG, JPG, or JPEG, preview the extracted table for accuracy, optionally chat with RowSpeak to clean or analyze the data, then export as XLSX. Numbers are preserved in separate cells ready for formulas and charts. RowSpeak also offers related workflows for invoice line-item extraction and PDF-to-Excel conversion, making it valuable for analysts, accountants, and researchers digitizing paper or image-based records.",
  category: "Coding",
  rating: 4.3,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=rowspeak.ai&sz=64",
  website: "https://rowspeak.ai",
  features: ["AI table structure detection", "Image to editable XLSX export", "Preserves rows, columns & merged cells", "AI chat to clean & analyze data", "Invoice & receipt extraction", "Preview before download"]
},
{
  id: 40,
  name: "KeyAPI",
  description: "AI-agent-first unified API giving developers one key to access data from 20+ social media platforms including TikTok, Instagram, and YouTube.",
  fullDescription: "KeyAPI is an AI-agent-first platform offering a unified REST API to access structured data from over 20 global social media and commerce platforms — TikTok, Instagram, Twitter, YouTube, Reddit, LinkedIn, Facebook, Amazon, Pinterest, and more — through a single API key. It returns clean JSON for profiles, posts, analytics, videos, comments, transcripts, and commerce signals, with under 500ms average latency and a 99.9% uptime SLA. Built for LLM pipelines, automation systems, and autonomous agents, KeyAPI integrates with the Model Context Protocol (MCP) and supports real-time plus historical data up to 1,000 days. Credit-based plans range from a free trial of 100 API calls up to Ultra at $699/31 days for 500,000 credits, eliminating the need for fragmented platform integrations and multi-key management.",
  category: "Coding",
  rating: 4.3,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=keyapi.ai&sz=64",
  website: "https://keyapi.ai",
  features: ["Unified API for 20+ platforms", "MCP integration for AI agents", "Under 500ms latency", "Historical data up to 1,000 days", "Clean structured JSON output", "99.9% uptime SLA"]
},
{
  id: 41,
  name: "Fliki AI",
  description: "AI text-to-video and text-to-speech platform with 2,500+ voices, AI avatars, and Veo 3 integration for faceless content creation.",
  fullDescription: "Fliki AI is an all-in-one text-to-video and text-to-speech platform that turns scripts, blog posts, URLs, or PowerPoint files into polished videos using a simple slide-based editor. Each slide automatically receives an AI voiceover from a library of 2,500+ ultra-realistic voices across 80+ languages, matched visuals from millions of stock clips or AI-generated imagery, and auto-subtitles. Recent integrations with Seedance 2.0 and Google's Veo 3 bring cinema-quality video generation directly into the platform. Voice cloning lets creators replicate their own voice for personal branding. With over 4 million users and a 4.7-4.8/5 rating across review platforms, Fliki is widely used for faceless YouTube channels, TikTok content, e-learning videos, and blog-to-video repurposing. A free plan offers 5 minutes of monthly content, with paid plans starting around $8-28/month.",
  category: "Video",
  rating: 4.6,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=fliki.ai&sz=64",
  website: "https://fliki.ai",
  features: ["2,500+ AI voices in 80+ languages", "Voice cloning", "Veo 3 & Seedance 2.0 integration", "Slide-based text-to-video editor", "10M+ stock media library", "Blog/URL to video conversion"]
},  
{
  id: 42,
  name: "Supernormal",
  description: "Bot-free AI meeting assistant that automatically transcribes, summarizes, and tracks action items across Zoom, Meet, and Teams.",
  fullDescription: "Supernormal is an AI meeting assistant that automatically takes notes, generates summaries, and tracks action items during meetings — without an awkward bot joining the call. Using its Radiant bot-free technology, it integrates directly with Google Meet, Zoom, and Microsoft Teams to capture key points, decisions, and tasks in real time. Notes are automatically formatted using customizable templates for sales, recruiting, project management, and executive briefings, then centralized and searchable across your team's workspace. Action items sync automatically with tools like Asana, ClickUp, Linear, HubSpot, and Salesforce. With 60+ language support, SOC 2 certification, and trusted by 250,000+ teams including Google and Spotify, Supernormal offers a free plan with unlimited meetings and up to 1,000 minutes of storage, with paid plans from $10-19/user/month.",
  category: "Text Generation",
  rating: 4.5,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=supernormal.com&sz=64",
  website: "https://supernormal.com",
  features: ["Bot-free meeting transcription", "Automatic action item tracking", "60+ language support & translation", "Custom note templates", "Zoom, Meet & Teams integration", "SOC 2 certified security"]
},
{
  id: 43,
  name: "HypeAuditor",
  description: "AI-powered influencer marketing platform with a 68M+ creator database for fraud detection, audience analysis, and campaign management.",
  fullDescription: "HypeAuditor is a comprehensive influencer marketing platform covering the entire campaign lifecycle from discovery to reporting. Its AI-powered database contains over 68 million influencer accounts across Instagram, YouTube, TikTok, Twitch, and Twitter, updated daily and searchable across 253 countries by niche. Originally built as a fraud detection tool, it remains industry-leading at identifying fake followers and bot engagement, alongside audience quality scoring, competitor analysis, and CRM tools for managing creator relationships. Campaign management features include outreach automation, performance tracking, and e-commerce integrations. HypeAuditor also offers full-service campaign management where experts handle creator negotiation and strategy. Plans start at $299/month billed annually, with all tiers including the same core modules but differing in usage limits and access to AI Search and advanced filters.",
  category: "Text Generation",
  rating: 4.4,
  pricing: "Paid",
  icon: "https://www.google.com/s2/favicons?domain=hypeauditor.com&sz=64",
  website: "https://hypeauditor.com",
  features: ["68M+ influencer database", "AI fraud & fake follower detection", "Audience quality analysis", "Campaign management & CRM", "Competitor analysis", "253 country coverage"]
},
{
  id: 44,
  name: "SchemaWriter.ai",
  description: "AI tool that automates JSON-LD schema markup generation for SEO using competitor entity analysis and Wikipedia/Wikidata data.",
  fullDescription: "SchemaWriter.ai automates the creation of advanced JSON-LD schema markup for on-page SEO optimization. Given a target search term and URL, it crawls the top 10 Google results, extracts relevant entities, and cross-references them with Wikipedia, Wikidata, and Google Knowledge Graph to generate structured data that helps search engines understand your content. Its YAKE keyword analysis identifies important terms from competitor pages, while entity gap analysis shows what your page is missing compared to top performers. A no-code editor lets users customize generated schema before deployment, with specialized templates including GeoRadius schema for local SEO. Plans run from $59/month (50 runs) to $119/month (150 runs, includes GeoRadius), and users supply their own OpenAI API key to keep software costs lower.",
  category: "Text Generation",
  rating: 4.1,
  pricing: "Paid",
  icon: "https://www.google.com/s2/favicons?domain=schemawriter.ai&sz=64",
  website: "https://schemawriter.ai",
  features: ["Automated JSON-LD schema generation", "Competitor entity extraction", "Wikipedia & Wikidata integration", "YAKE keyword gap analysis", "No-code schema editor", "GeoRadius schema for local SEO"]
},
{
  id: 45,
  name: "HyNote",
  description: "All-in-one AI note-taking app that transcribes audio, summarizes PDFs and YouTube videos, and extracts text from images via OCR.",
  fullDescription: "HyNote is an AI-powered note-taking and productivity platform that turns information from any source — audio, PDFs, images, YouTube videos, and web pages — into structured, actionable notes. Its AI Core Engine provides 99% accurate audio transcription with speaker identification in 50+ languages, OCR-based image and document text extraction, smart text summarization with customizable formats, and one-click web page summarization from a URL. Outputs include meeting summaries, flashcards, quizzes, and action items, exportable to PDF or Word. With encrypted storage compliant with GDPR, CCPA, and HIPAA, integrations with Google Docs and Notion, and cross-device sync across web, iOS, Android, and Chrome Extension, HyNote serves over 1 million users as an AI-powered 'second brain.' The free plan includes 300 AI credits and a 7-day trial, with paid plans starting at $6.66-10.83/month.",
  category: "Text Generation",
  rating: 4.3,
  pricing: "Freemium",
  icon: "https://www.google.com/s2/favicons?domain=hynote.ai&sz=64",
  website: "https://hynote.ai",
  features: ["AI audio transcription (99% accuracy)", "PDF & YouTube summarization", "OCR image text extraction", "Speaker identification (50+ languages)", "Google Docs & Notion integration", "Cross-device sync (web, iOS, Android)"]
},  
];

// Categories derived from data
const CATEGORIES = [...new Set(AI_TOOLS.map(t => t.category))].sort();
